### PR TITLE
UI improvements 

### PR DESCRIPTION
**Pull request by huzaifsk**
Update the styling of the background #1

changed navbar background
improved user items card and added animation to it changed text color of locations
added condition in location image for a better experience
changed the background and added gradient

### CODE REVIEW

**Comment by rohitja26** [comment]
@huzaifsk  Please share the screenshot of the changes that you have made here as I am unable to find anything that you have changed. You just cut and paste the things again

**Comment by huzaifsk** [comment]
image
image

**Comment by huzaifsk** [comment]
@rohitja26 attached screenshots please check

**Comment by rohitja26** [comment]
ohhk

**Pull request merged**
